version: '3.3'
services:
  mongo:
    container_name: mymongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - tomnet
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command: redis-server --requirepass 123456
    networks:
      - tomnet
  selfpro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selfpro
    ports:
      - "8000:8000"
      - "3000:3000"
      - "2222:22"
    volumes:
      - /Users/fanjunjie/Desktop/data/selfpro:/data
    depends_on:
      - mongo
    environment:
      - MONGO_URI="mongodb://root:root@mongo:27017/admin?authSource=admin"
    networks:
      - tomnet
networks:
  tomnet:
    driver:bridge
    
    
      
