version: '3.3'
services:
  mongo:
    container_name: mymongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /Users/fanjunjie/Desktop/data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  selfpro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selfpro
    ports:
      - "8000:8000"
      - "3000:3000"
      - "2222:22"
    volumes:
      - /Users/fanjunjie/Desktop/data/selfpro:/data
    depends_on:
      - mongo
    environment:
      - MONGO_URI:"mongodb://root:root@mongo:27017/admin?authSource=admin"
      
