services:
  mysql:
    container_name: onenet_mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: tom
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: yes # 如果需要不进行密码验证则必须设置此项
    ports:
      - 8306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    
  redis:
    container_name: onenet_redis
    image: redis:latest
    restart: always
    ports:
      - 8379:6379
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass "123456" # 设置密码，不设置此项连接时不需要密码验证

  mongo:
    container_name: onenet_mongo
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongo/data:/data
    environment:
      # 不设置这两项则不进行验证
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  minio:
    container_name: onenet_minio
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address :9001

  rabbitmq:
    container_name: onenet_rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/

  influxdb:
    container_name: onenet_influxdb
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

networks:
  onenet:
    external: true
    name: onenet